sudo: false
dist: trusty

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=mysql IMAGE=mysql:5.5
  - DB=mysql IMAGE=mysql:5.6
  - DB=mysql IMAGE=mysql:5.7
  - DB=mysql IMAGE=mysql:8.0

  - DB=mysql IMAGE=mariadb:5.5
  - DB=mysql IMAGE=mariadb:10.0
  - DB=mysql IMAGE=mariadb:10.1
  
  - DB=mysql IMAGE=percona:5.5
  - DB=mysql IMAGE=percona:5.6
  - DB=mysql IMAGE=percona:5.7

  - DB=pgsql IMAGE=postgres:9.2
  - DB=pgsql IMAGE=postgres:9.3
  - DB=pgsql IMAGE=postgres:9.4
  - DB=pgsql IMAGE=postgres:9.5
  - DB=pgsql IMAGE=postgres:9.6

before_script:
  - docker pull $IMAGE
  - composer self-update
  - composer update --prefer-dist
  - vendor/bin/phpunit --configuration tests/config/$DB.phpunit.xml tests/Oro/Tests/Connection/SetupTest.php

after_success:
  - vendor/bin/phpunit --configuration tests/config/$DB.phpunit.xml tests/Oro/Tests/Connection/TearDownTest.php

script: vendor/bin/phpunit --configuration tests/config/$DB.phpunit.xml --testsuite="Oro Doctrine Extensions Test Suite"
